title:              Won's blog
email:              wonnn0801@hufs.ac.kr
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
url:                "https://wonnn0801.github.io"

# Social Profiles
github_username:    wonnn0801
instagram_username: won_12_
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
